# Generated by Django 2.2.4 on 2019-08-07 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FlowControling', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='healthdata',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='bleeding',
            field=models.IntegerField(choices=[(0, '-'), (1, 'słabe'), (2, 'umiarkowane'), (3, 'obfite')]),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='energy',
            field=models.IntegerField(choices=[(0, '-'), (1, 'niski'), (2, 'wysoki'), (3, 'wyczerpany')]),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='mood',
            field=models.IntegerField(choices=[(0, '-'), (1, 'radosny'), (2, 'wrażliwy'), (3, 'smutny'), (4, 'PMS')]),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='notes',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='pain',
            field=models.IntegerField(choices=[(0, '-'), (1, 'słaby'), (2, 'umiarkowany'), (3, 'silny')]),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='sex',
            field=models.IntegerField(choices=[(0, '-'), (1, 'z zabezpieczeniem'), (2, 'bez zabezpieczenia')]),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
