# Generated by Django 2.2.4 on 2020-03-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlowControling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthdata',
            name='different',
            field=models.IntegerField(choices=[(0, 'wybierz'), (1, 'ból piersi'), (2, 'Obrzęk piersi'), (3, 'Bóle mięśni'), (4, 'Bezsenność'), (5, 'Ból głowy'), (6, 'Libido podniesione'), (7, 'Libido obniżone')], default=0),
            preserve_default=False,
        ),
    ]
