# Generated by Django 2.2.4 on 2019-08-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlowControling', '0002_auto_20190805_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdata',
            name='bleeding',
            field=models.IntegerField(blank=True, choices=[(0, 'brak'), (1, 'słabe'), (2, 'umiarkowane'), (3, 'obfite')], null=True),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='energy',
            field=models.IntegerField(blank=True, choices=[(1, 'niski'), (2, 'wysoki'), (3, 'wyczerpany')], null=True),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='mood',
            field=models.IntegerField(blank=True, choices=[(1, 'radosny'), (2, 'wrażliwy'), (3, 'smutny'), (4, 'PMS')], null=True),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='notes',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='pain',
            field=models.IntegerField(blank=True, choices=[(1, 'słaby'), (2, 'umiarkowany'), (3, 'silny')], null=True),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(1, 'z zabezpieczeniem'), (2, 'bez zabezpieczenia')], null=True),
        ),
    ]
