# Generated by Django 2.2.4 on 2019-08-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlowControling', '0003_auto_20190806_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdata',
            name='bleeding',
            field=models.IntegerField(choices=[(0, ''), (1, 'brak'), (2, 'słabe'), (3, 'umiarkowane'), (4, 'obfite')]),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='energy',
            field=models.IntegerField(choices=[(0, ''), (1, 'niski'), (2, 'wysoki'), (3, 'wyczerpany')]),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='mood',
            field=models.IntegerField(choices=[(0, ''), (1, 'radosny'), (2, 'wrażliwy'), (3, 'smutny'), (4, 'PMS')]),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='notes',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='pain',
            field=models.IntegerField(choices=[(0, ''), (1, 'słaby'), (2, 'umiarkowany'), (3, 'silny')]),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='sex',
            field=models.IntegerField(choices=[(0, ''), (1, 'z zabezpieczeniem'), (2, 'bez zabezpieczenia')]),
        ),
    ]
