# Generated by Django 2.2.4 on 2020-03-31 10:42

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('FlowControling', '0004_auto_20200331_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdata',
            name='bleeding',
            field=models.IntegerField(choices=[(0, 'wybierz'), (1, 'Słabe'), (2, 'Umiarkowane'), (3, 'Obfite'), (4, 'Plamienie')]),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='different',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Bolesne piersi'), (2, 'Obrzęk piersi'), (3, 'Bóle mięśni'), (4, 'Bezsenność'), (5, 'Ból głowy'), (6, 'Libido podniesione'), (7, 'Libido obniżone')], max_length=13),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='energy',
            field=models.IntegerField(choices=[(0, 'wybierz'), (1, 'Niski'), (2, 'Wysoki'), (3, 'Wyczerpany')]),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='mood',
            field=models.IntegerField(choices=[(0, 'wybierz'), (1, 'Radosny'), (2, 'Wrażliwy'), (3, 'Smutny'), (4, 'PMS'), (5, 'Płaczliwość'), (6, 'Niepokój')]),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='pain',
            field=models.IntegerField(choices=[(0, 'wybierz'), (1, 'Słaby'), (2, 'Umiarkowany'), (3, 'Silny')]),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='sex',
            field=models.IntegerField(choices=[(0, 'wybierz'), (1, 'Z zabezpieczeniem'), (2, 'Bez zabezpieczenia')]),
        ),
    ]
