# Generated by Django 2.2.4 on 2019-08-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlowControling', '0005_auto_20190806_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdata',
            name='notes',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
