# Generated by Django 2.2.4 on 2019-08-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlowControling', '0006_auto_20190806_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdata',
            name='bleeding',
            field=models.IntegerField(blank=True, choices=[(0, '-'), (1, 'brak'), (2, 'słabe'), (3, 'umiarkowane'), (4, 'obfite')]),
        ),
    ]
