# Generated by Django 2.2.4 on 2019-08-06 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FlowControling', '0007_auto_20190806_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthdata',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='bleeding',
            field=models.IntegerField(choices=[(0, '-'), (1, 'brak'), (2, 'słabe'), (3, 'umiarkowane'), (4, 'obfite')]),
        ),
    ]
