# Generated by Django 2.2.4 on 2019-08-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlowControling', '0008_auto_20190806_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdata',
            name='bleeding',
            field=models.IntegerField(choices=[(0, '-'), (1, 'słabe'), (2, 'umiarkowane'), (3, 'obfite')]),
        ),
    ]
